spring:
  application:
    name: CallAutomation_OutboundCalling

server:
  port: 8080

acs:
  connectionstring: <YOUR ACS CONNECTION STRING>
  basecallbackuri: <YOUR DEV TUNNEL ENDPOINT>
  cognitiveServicesUrl: <YOUR COGNITIVE SERVICE ENDPOINT>
  agentPhoneNumber: ""
  isPauseOnStart": "true"
  isByos": "true"
  bringYourOwnStorageUrl: ""
  teamsComplianceUserId: ""
  isTeamsComplianceUser: "false"
  acsPhonenumber: <YOUR ACS PHONE NUMBER ex. "+1425XXXAAAA">
  targetPhonenumber: <YOUR TARGET PHONE NUMBER ex. "+1425XXXAAAA">
  isRejectCall: "false"
  isCancelAddParticipant: "false"
