spring:
  application:
    name: CallAutomation_OutboundCalling

server:
  port: 8080

acs:
  connectionstring: 
  basecallbackuri: 
  cognitiveServicesUrl: 
  agentPhoneNumber: ""
  isPauseOnStart": "false"
  isByos": "false"
  bringYourOwnStorageUrl: ""
  teamsComplianceUserId: ""
  isTeamsComplianceUser: "false"
  acsPhonenumber: ""
  targetPhonenumber: ""
  isRejectCall: "false"
  isCancelAddParticipant: "false"
