spring:
  application:
    name: CallAutomation_OutboundCalling

server:
  port: 8080

acs:
  connectionstring: 
  basecallbackuri: 
  callerphonenumber: ""
  targetphonenumber: ""
  cognitiveServiceEndpoint: 
  webSocketUrl: ""
  targetTeamsUserId: <(OPTIONAL) YOUR TARGET TEAMS USER ID ex. "ab01bc12-d457-4995-a27b-c405ecfe4870">
