spring:
  application:
    name: CallAutomation_OutboundCalling

server:
  port: 8080

acs:
  connectionstring: <YOUR ACS CONNECTION STRING>
  basecallbackuri: <YOUR DEV TUNNEL ENDPOINT>
  callerphonenumber: <YOUR ACS PHONE NUMBER ex. "+1425XXXAAAA">
  targetphonenumber: <YOUR TARGET PHONE NUMBER ex. "+1425XXXAAAA">
  cognitiveServiceEndpoint: <YOUR COGNITIVE SERVICE ENDPOINT>
  isPauseOnStart": "false"
  isByos": "true"
  bringYourOwnStorageUrl: <YOUR AZURE BLOB STORAGE URI>
