spring:
  application:
    name: CallAutomation_PlayAndRecognize

server:
  port: 8080

acs:
  connectionstring: <YOUR ACS CONNECTION STRING>
  basecallbackuri: <YOUR DEV TUNNEL ENDPOINT>
  cognitiveserviceendpoint: <COGNITIVE SERVICE ENDPOINT>
  usephone: false
  targetuserid: <YOUR TARGET USER ID>
  callerphonenumber: <YOUR ACS PHONE NUMBER ex. "+1425XXXAAAA">
  targetphonenumber: <YOUR TARGET PHONE NUMBER ex. "+1425XXXAAAA">
